<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit(); // Exit if accessed directly
}

class WPBakeryShortCode_DT_Video_Player extends DTWPBakeryShortcode {}
vc_map( 
	array( 
		'base' => 'dt_video_player',
		'name' => esc_html__( 'Video Player', 'viem' ), 
		'description' => esc_html__( 'Display a Playlist.', 'viem' ), 
		"category" => esc_html__( "DawnThemes", 'viem' ), 
		'class' => 'dt-vc-element dt-vc-element-dt_video',
		'icon' => 'dt-vc-icon-dt_video', 
		'show_settings_on_create' => true, 
		'params' => array(
			array(
				'param_name' => 'title',
				'heading' => esc_html__( 'Title', 'viem' ),
				'description' => '',
				'type' => 'textfield',
				'value' => '',
				'admin_label' => true ),
			array(
				'type' => 'attach_image',
				'heading' => esc_html__( 'Thumbnail', 'viem' ),
				'param_name' => 'video_thumb',
			),
			array(
				'type' => 'dropdown',
				'heading' => esc_html__( 'video player type', 'viem' ),
				'param_name' => 'video_type',
				'std' => 'youtube',
				'value' => array(
					esc_html__( 'YouTube', 'viem' ) => 'youtube',
					esc_html__( 'Vimeo', 'viem' ) => 'vimeo',
					esc_html__( 'HTML5 (self-hosted)', 'viem' ) => 'HTML5',
				),
				'description' => esc_html__( 'Select video player type.', 'viem' )
			),
			array(
				'param_name' => 'youtube_id',
				'heading' => esc_html__( 'YouTube ID', 'viem' ),
				'description' => esc_html__( 'last part of the URL https://www.youtube.com/watch?v=0dJO0HyE8xE', 'viem' ),
				'type' => 'textfield',
				'dependency' => array( 'element' => "video_type", 'value' => array( 'youtube') ),
			),
			array(
				'param_name' => 'vimeo_id',
				'heading' => esc_html__( 'Vimeo ID', 'viem' ),
				'description' => esc_html__( 'last part of the URL http://vimeo.com/119641053', 'viem' ),
				'type' => 'textfield',
				'dependency' => array( 'element' => "video_type", 'value' => array( 'vimeo') ),
			),
			array(
				'param_name' => 'video_mp4',
				'heading' => esc_html__( 'MP4 Video URL', 'viem' ),
				'description' => esc_html__( 'HTML5 video mp4, HLS m3u8 (url)', 'viem' ),
				'type' => 'textfield',
				'dependency' => array( 'element' => "video_type", 'value' => array( 'HTML5') ),
			),
			array(
				'type' => 'dropdown',
				'heading' => esc_html__( 'Select Player Theme', 'viem' ),
				'param_name' => 'video_instance_theme',
				'std' => 'dark',
				'value' => array(
					esc_html__( 'Dark', 'viem' ) => 'dark', 
					esc_html__( 'Light', 'viem' ) => 'light',
				),
			),
			array(
				'type' => 'dropdown',
				'heading' => esc_html__( 'Select player shadow', 'viem' ),
				'param_name' => 'video_player_shadow',
				'std' => 'off',
				'value' => array(
					esc_html__( 'off', 'viem' ) => 'off', 
					esc_html__( 'effect1', 'viem' ) => 'effect1',
					esc_html__( 'effect2', 'viem' ) => 'effect2',
					esc_html__( 'effect3', 'viem' ) => 'effect3',
					esc_html__( 'effect4', 'viem' ) => 'effect4',
					esc_html__( 'effect5', 'viem' ) => 'effect5',
					esc_html__( 'effect6', 'viem' ) => 'effect6', 
				),
			),
			array(
				'type' => 'dropdown', 
				'heading' => esc_html__( 'Video aspect ration', 'viem' ), 
				'param_name' => 'video_ratio', 
				'std' => '169', 
				'value' => array( 
					'16:9' => '169',
					'4:3' => '43',
					'3:2' => '32',
					'21:9' => '219',
				),
				"description" => esc_html__( "Select video aspect ratio.", 'viem' )
			),
			array( 
				'type' => 'dropdown', 
				'heading' => esc_html__( 'Auto Play', 'viem' ), 
				'param_name' => 'auto_play', 
				'std' => 'off', 
				'value' => array( esc_html__( 'OFF', 'viem' ) => 'off', esc_html__( 'ON', 'viem' ) => 'on' ), ),
			array( 
				'type' => 'dropdown', 
				'heading' => esc_html__( 'Sticky player', 'viem' ), 
				'description' => esc_html__( 'Sticky player if not in viewport when scrolling through page', 'viem' ), 
				'param_name' => 'sticky_player', 
				'std' => 1, 
				'value' => array( esc_html__( 'OFF', 'viem' ) => 0, esc_html__( 'ON', 'viem' ) => 1 ), ),
			array( 
				'type' => 'dropdown', 
				'heading' => esc_html__( 'Show Pre Roll Video Ad?', 'viem' ),
				'description' => esc_html__( 'Pre Roll advertisement will show at the start of the video.', 'viem' ),
				'param_name' => 'preroll_ad', 
				'std' => 'no',
				'group' => esc_html__( 'Pre Roll Ads', 'viem' ),
				'value' => array( esc_html__( 'No', 'viem' ) => 'no', esc_html__( 'Yes', 'viem' ) => 'yes' ), ),
			array(
				'param_name' => 'preroll_goto_link',
				'heading' => esc_html__( 'Pre Roll Video Ad Link URL', 'viem' ),
				'description' => esc_html__( 'pre-roll goto link.', 'viem' ),
				'type' => 'textfield',
				'group' => esc_html__( 'Pre Roll Ads', 'viem' ),
				'dependency' => array( 'element' => "preroll_ad", 'value' => array( 'yes')),
			),
			array(
				'param_name' => 'preroll_mp4',
				'heading' => esc_html__( 'Pre Roll Video Ad MP4 , HLS m3u8 (url)', 'viem' ),
				'description' => esc_html__( 'pre-roll video mp4 format, HLS m3u8', 'viem' ),
				'type' => 'textfield',
				'group' => esc_html__( 'Pre Roll Ads', 'viem' ),
				'dependency' => array( 'element' => "preroll_ad", 'value' => array( 'yes')),
			),
			array(
				'param_name' => 'preroll_skip_timer',
				'heading' => esc_html__( 'Pre Roll Video Skip Timer', 'viem' ),
				'description' => esc_html__( '(sec)', 'viem' ),
				'type' => 'textfield',
				'value' => 5,
				'group' => esc_html__( 'Pre Roll Ads', 'viem' ),
				'dependency' => array( 'element' => "preroll_ad", 'value' => array( 'yes')),
			),

			array( 
				'type' => 'dropdown', 
				'heading' => esc_html__( 'Show Mid Roll Video Ad?', 'viem' ),
				'description' => esc_html__( 'Show Mid Roll advertisement at any custom time in format "minutes:seconds" ("00:00")', 'viem' ),
				'param_name' => 'midroll_ad', 
				'std' => 'no',
				'group' => esc_html__( 'Mid Roll Ads', 'viem' ),
				'value' => array( esc_html__( 'No', 'viem' ) => 'no', esc_html__( 'Yes', 'viem' ) => 'yes' ), ),
			array(
				'param_name' => 'midrollad_display_Time',
				'heading' => esc_html__( 'Mid Roll Video Ad Display Time', 'viem' ),
				'description' => esc_html__( '"minutes:seconds" ("00:00")', 'viem' ),
				'type' => 'textfield',
				'value' => 5,
				'group' => esc_html__( 'Mid Roll Ads', 'viem' ),
				'dependency' => array( 'element' => "midroll_ad", 'value' => array( 'yes')),
			),
			array(
				'param_name' => 'midroll_goto_link',
				'heading' => esc_html__( 'Mid Roll Video Ad Link URL', 'viem' ),
				'description' => esc_html__( 'mid-roll goto link.', 'viem' ),
				'type' => 'textfield',
				'group' => esc_html__( 'Mid Roll Ads', 'viem' ),
				'dependency' => array( 'element' => "midroll_ad", 'value' => array( 'yes')),
			),
			array(
				'param_name' => 'midroll_mp4',
				'heading' => esc_html__( 'Mid Roll Video Ad MP4 , HLS m3u8 (url)', 'viem' ),
				'description' => esc_html__( 'mid-roll video mp4 format, HLS m3u8.', 'viem' ),
				'type' => 'textfield',
				'group' => esc_html__( 'Mid Roll Ads', 'viem' ),
				'dependency' => array( 'element' => "midroll_ad", 'value' => array( 'yes')),
			),
			array(
				'param_name' => 'midroll_skip_timer',
				'heading' => esc_html__( 'Mid Roll Video Skip Timer', 'viem' ),
				'description' => esc_html__( '(sec)', 'viem' ),
				'type' => 'textfield',
				'value' => 5,
				'group' => esc_html__( 'Mid Roll Ads', 'viem' ),
				'dependency' => array( 'element' => "midroll_ad", 'value' => array( 'yes')),
			),

			array( 
				'type' => 'dropdown', 
				'heading' => esc_html__( 'Show Post Roll Video Ad?', 'viem' ),
				'description' => esc_html__( 'Post Roll advertisement will show at the end of the video.', 'viem' ),
				'param_name' => 'postroll_ad', 
				'std' => 'no',
				'group' => esc_html__( 'Post Roll Ads', 'viem' ),
				'value' => array( esc_html__( 'No', 'viem' ) => 'no', esc_html__( 'Yes', 'viem' ) => 'yes' ), ),
			array(
				'param_name' => 'postroll_skip_timer',
				'heading' => esc_html__( 'Mid Roll Video Ad Display Time', 'viem' ),
				'description' => esc_html__( '"minutes:seconds" ("00:00")', 'viem' ),
				'type' => 'textfield',
				'value' => 5,
				'group' => esc_html__( 'Post Roll Ads', 'viem' ),
				'dependency' => array( 'element' => "postroll_ad", 'value' => array( 'yes')),
			),
			array(
				'param_name' => 'postroll_goto_link',
				'heading' => esc_html__( 'Post Roll Video Ad Link URL', 'viem' ),
				'description' => esc_html__( 'mid-roll goto link.', 'viem' ),
				'type' => 'textfield',
				'group' => esc_html__( 'Post Roll Ads', 'viem' ),
				'dependency' => array( 'element' => "postroll_ad", 'value' => array( 'yes')),
			),
			array(
				'param_name' => 'postroll_mp4',
				'heading' => esc_html__( 'Post Roll Video Ad MP4 , HLS m3u8 (url)', 'viem' ),
				'description' => esc_html__( 'mid-roll video mp4 format, HLS m3u8.', 'viem' ),
				'type' => 'textfield',
				'group' => esc_html__( 'Post Roll Ads', 'viem' ),
				'dependency' => array( 'element' => "postroll_ad", 'value' => array( 'yes')),
			),

			array( 
				'type' => 'dropdown', 
				'heading' => esc_html__( 'Show Pop-up Ad?', 'viem' ),
				'description' => esc_html__( 'You can set when to show and hide pop-up image ad (in format minutes:seconds).', 'viem' ),
				'param_name' => 'popup_ad_show', 
				'std' => 'no',
				'group' => esc_html__( 'PopUp Ads', 'viem' ),
				'value' => array( esc_html__( 'No', 'viem' ) => 'no', esc_html__( 'Yes', 'viem' ) => 'yes' ), ),
			array(
				'type' => 'attach_image',
				'heading' => esc_html__( 'Popup Image', 'viem' ),
				'param_name' => 'popup_img',
				'group' => esc_html__( 'PopUp Ads', 'viem' ),
				'dependency' => array( 'element' => "popup_ad_show", 'value' => array( 'yes')),
			),
			array(
				'param_name' => 'popup_ad_start_time',
				'heading' => esc_html__( 'Pop-up Ad Start Time', 'viem' ),
				'description' => esc_html__( 'Time to show popup ad during playback (sec)', 'viem' ),
				'type' => 'textfield',
				'value' => '00:03',
				'group' => esc_html__( 'PopUp Ads', 'viem' ),
				'dependency' => array( 'element' => "popup_ad_show", 'value' => array( 'yes')),
			),
			array(
				'param_name' => 'popup_ad_end_time',
				'heading' => esc_html__( 'Pop-up Ad End Time', 'viem' ),
				'description' => esc_html__( 'Time to hide popup ad during playback (sec)', 'viem' ),
				'type' => 'textfield',
				'value' => '00:07',
				'group' => esc_html__( 'PopUp Ads', 'viem' ),
				'dependency' => array( 'element' => "popup_ad_show", 'value' => array( 'yes')),
			),
			array(
				'param_name' => 'popup_ad_goto_link',
				'heading' => esc_html__( 'Pop-up Ad Link URL', 'viem' ),
				'description' => esc_html__( 're-direct to URL when popup ad clicked.', 'viem' ),
				'type' => 'textfield',
				'group' => esc_html__( 'PopUp Ads', 'viem' ),
				'dependency' => array( 'element' => "popup_ad_show", 'value' => array( 'yes')),
			),
			
			array(
				'param_name' => 'el_class', 
				'heading' => esc_html__( '(Optional) Extra class name', 'viem' ), 
				'type' => 'textfield', 
				'value' => '', 
				"description" => esc_html__( 
					"If you wish to style particular content element differently, then use this field to add a class name and then refer to it in your css file.", 
					'viem' ) ),
			array(
				'type' => 'css_editor',
				'heading' => esc_html__( 'Css', 'viem' ),
				'param_name' => 'css',
				'group' => esc_html__( 'Design options', 'viem' ) ) ) ) );